server:
  port: 7003

spring:
  application:
    name: feign-client

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
  instance:
    lease-expiration-duration-in-seconds: 2
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 1
    #将ip注册到eureka server上而不是机器主机名
    prefer-ip-address: true
    #ip-address: 127.0.0.1
    #InstanceId默认是${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}},
    #也就是：主机名：应用名：应用端口
    #通过instance-id 自定义ip+端口号
    instance-id: ${spring.cloud.client.ipaddress}:${server.port}
