server:
  port: 1201

spring:
  application:
    name: config-server
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          # Git 仓库位置
          uri: https://github.com/gexiaoshan518/spring-cloud.git
          # 访问 Git 仓库的用户名
          username:
          # 访问 Git 仓库的密码
          password:
          # 仓库路径下相对搜索位置，可配置多个
          search-paths: 'config-server/src/main/resources/{application}'
          #force-pull: true
#        native:
#          searchLocations: E:/config
  #加密，配置用户名密码
  security:
    user:
      name: admin
      password: 123456