spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gexiaoshan518/spring-cloud.git
          username:
          password:
#          default-label: ${spring.profiles.active}
          search-paths: 'config-server/src/main/resources/{application}'
          force-pull: true
server:
  port: 1201